version: "3.9"

services:
  db-container:
    restart: always
    container_name: postgres-db-container
    build:
      context: .
      dockerfile: './postgres/Dockerfile'
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      PGDATA: "/var/lib/postgresql/data/pgdata"
    volumes:
      - .:/var/lib/postgresql/data
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    networks:
      - application

  nest-container:
    container_name: nest-service-container
    restart: unless-stopped
    build:
      context: .
      target: development
    depends_on:
      - postgres-container
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - ${PORT}:${PORT}
#    command: npm run start:dev
    env_file:
      - .env
    networks:
      - application

networks:
  application:
    driver: bridge
